In [9]:
import os

In [10]:
import numpy as np
import cv2
from tensorflow.keras.utils import to_categorical

from keras.layers import Input, Dense 
from keras.models import Model

In [11]:
is_init = False
size = -1

label = []
dictionary = {}
c = 0

for i in os.listdir():
    if i.split(".")[-1] == "npy" and not(i.split(".")[0] == "labels"):  
        if not(is_init):
            is_init = True 
            X = np.load(i)
            size = X.shape[0]
            y = np.array([i.split('.')[0]]*size).reshape(-1,1)
        else:
            X = np.concatenate((X, np.load(i)))
            y = np.concatenate((y, np.array([i.split('.')[0]]*size).reshape(-1,1)))

        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c  
        c = c+1


for i in range(y.shape[0]):
    y[i, 0] = dictionary[y[i, 0]]
y = np.array(y, dtype="int32")

###  hello = 0 nope = 1 ---> [1,0] ... [0,1]

y = to_categorical(y)

X_new = X.copy()
y_new = y.copy()
counter = 0 

cnt = np.arange(X.shape[0])
np.random.shuffle(cnt)

for i in cnt: 
    X_new[counter] = X[i]
    y_new[counter] = y[i]
    counter = counter + 1


ip = Input(shape=(X.shape[1]))

m = Dense(512, activation="relu")(ip)
m = Dense(256, activation="relu")(m)

op = Dense(y.shape[1], activation="softmax")(m) 

model = Model(inputs=ip, outputs=op)

model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])

model.fit(X, y, epochs=50)


model.save("model.h5")
np.save("labels.npy", np.array(label))


Epoch 1/50
29/29 [==============================] - 0s 3ms/step - loss: 2.0109 - acc: 0.2733
Epoch 2/50
29/29 [==============================] - 0s 3ms/step - loss: 1.6567 - acc: 0.4211
Epoch 3/50
29/29 [==============================] - 0s 3ms/step - loss: 1.3866 - acc: 0.5222
Epoch 4/50
29/29 [==============================] - 0s 3ms/step - loss: 1.2729 - acc: 0.5522
Epoch 5/50
29/29 [==============================] - 0s 3ms/step - loss: 1.1938 - acc: 0.5844
Epoch 6/50
29/29 [==============================] - 0s 3ms/step - loss: 1.0882 - acc: 0.6222
Epoch 7/50
29/29 [==============================] - 0s 3ms/step - loss: 1.0296 - acc: 0.6333
Epoch 8/50
29/29 [==============================] - 0s 3ms/step - loss: 0.9859 - acc: 0.6744
Epoch 9/50
29/29 [==============================] - 0s 3ms/step - loss: 0.8973 - acc: 0.6822
Epoch 10/50
29/29 [==============================] - 0s 3ms/step - loss: 0.8768 - acc: 0.7144
Epoch 11/50
29/29 [==============================] - 0s 3ms/step - lo

/Users/yuktisharma/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [12]:
print(X)
print(y)

[[ 0.0002982   0.06035966  0.         ...  0.          0.
   0.        ]
 [-0.00018102  0.06081235  0.         ...  0.          0.
   0.        ]
 [ 0.00101104  0.0610494   0.         ...  0.          0.
   0.        ]
 ...
 [ 0.00208116  0.0628075   0.         ...  0.          0.
   0.        ]
 [ 0.00201601  0.06255472  0.         ...  0.          0.
   0.        ]
 [ 0.00210246  0.06239593  0.         ...  0.          0.
   0.        ]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
